version: '3.8'
services:
  react-app:
    # Use your specific production private repo name
    image: krsh11/react-app-prod:latest
    container_name: react-app
    ports:
      - "80:80"  # This satisfies the Port 80 requirement
    restart: always
    